# https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2
sphinx:
  configuration: source/conf.py
build:
  os: ubuntu-20.04
  tools:
    python: "mambaforge-4.10"
  apt_packages:
    - rsync
    - git
  jobs:
    post_install:
      - git clone -v --depth=1 --single-branch --branch=_cookbook_data -- https://github.com/openforcefield/openff-docs.git build/_cookbook_data
      - rsync -a build/_cookbook_data/ ./
conda:
  environment: devtools/conda-envs/rtd_env.yml
