# https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2
sphinx:
  configuration: source/conf.py
build:
  os: ubuntu-20.04
  tools:
    python: "mambaforge-4.10"
  apt_packages:
    - rsync
  jobs:
    post_install:
      - |
        if [ "$READTHEDOCS_VERSION_TYPE" = "external" ]; then
          # This is a PR, so use the PR number
          CACHE_BRANCH="_cookbook_data_PR${READTHEDOCS_VERSION_NAME}"
        else
          # This is not a PR, so use the Git reference
          CACHE_BRANCH="_cookbook_data_${READTHEDOCS_GIT_IDENTIFIER}"
        fi
        git clone -v --depth=1 --single-branch --branch=${CACHE_BRANCH} -- https://github.com/openforcefield/openff-docs.git build/_cookbook_data
      - rsync -a "build/_cookbook_data"/* ./
conda:
  environment: devtools/conda-envs/rtd_env.yml
