# https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2
sphinx:
  configuration: source/conf.py
build:
  os: ubuntu-20.04
  tools:
    python: "mambaforge-4.10"
  apt_packages:
    - rsync
    - git
  jobs:
    post_install:
      - ls build/cookbook source .
      - git clone -v --depth=1 --single-branch --branch=_cookbook_data -- https://github.com/openforcefield/openff-docs.git build/_cookbook_data
      - |
        set -eu
        if [ "$READTHEDOCS_VERSION_TYPE" = "external" ]; then
          # This is a PR, so use the PR number
          rsync -a "build/_cookbook_data/PR${READTHEDOCS_VERSION_NAME}" ./
        else
          # This is not a PR, so use the Git reference
          rsync -a "build/_cookbook_data/${READTHEDOCS_GIT_IDENTIFIER}" ./
        fi
      - ls build/cookbook source .
conda:
  environment: devtools/conda-envs/rtd_env.yml
