# https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2
sphinx:
  configuration: source/conf.py
build:
  os: ubuntu-20.04
  tools:
    python: "mambaforge-4.10"
  apt_packages:
    - rsync
  jobs:
    post_install:
      - git clone -v --depth=1 --single-branch --branch=_cookbook_data -- https://github.com/openforcefield/openff-docs.git build/_cookbook_data
      - |
        CACHE_PREFIX = $(python -c "import sys; sys.path.append('source/_ext'); import cookbook; print(cookbook.get_cache_prefix())")
        rsync -a "build/_cookbook_data/${CACHE_PREFIX}"/* ./
conda:
  environment: devtools/conda-envs/rtd_env.yml
