# https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2
sphinx:
  configuration: source/conf.py
build:
  os: ubuntu-20.04
  tools:
    python: "mambaforge-4.10"
conda:
  environment: devtools/conda-envs/rtd_env.yml
