name: Pre-process example notebooks

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Update the cache for this PR (leave blank if not a PR)'
        required: false
        default: ""
        type: string
  schedule:
    - cron: 0 0 * * * # 1/day at midnight UTC

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Conda environment
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: devtools/conda-envs/examples_env.yml

      - name: Checkout deployment branch
        uses: actions/checkout@v3
        with:
          ref: _cookbook_data
          path: 'deploy'
          clean: false

      - name: Choose deployment subdirectory
        shell: bash -l {0}
        run: |
          if [[ ${{ github.event_name }} != "workflow_dispatch" ]]; then
            echo "DEPLOY_SUBDIR=$GITHUB_REF" >> "$GITHUB_ENV"
          elif [[ "${{ inputs.pr_number }}" == "" ]]; then
            echo "DEPLOY_SUBDIR=$GITHUB_REF" >> "$GITHUB_ENV"
          else
            echo "DEPLOY_SUBDIR=PR${{ inputs.pr_number }}" >> "$GITHUB_ENV"
          fi

      - name: Prepare cache deployment directory
        shell: bash -l {0}
        run: |
          mkdir -p deploy/$DEPLOY_SUBDIR
          cd deploy/$DEPLOY_SUBDIR
          git config user.name github-actions
          git config user.email github-actions@github.com
          git rm -r --ignore-unmatch .

      - name: Pre-process and execute notebooks
        shell: bash -l {0}
        run: |
          python source/_ext/proc_examples.py --prefix=deploy/$DEPLOY_SUBDIR

      - name: Deploy cache
        shell: bash -l {0}
        run: |
          cd deploy/$DEPLOY_SUBDIR
          git add .
          git commit --amend -m "Deploy pre-processed notebook cache"
          git push --force origin _cookbook_data
