name: Trigger preproc on comment with "/regenerate-cache"

on:
  issue_comment:
    types: [created]

jobs:
  trigger:
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest

    steps:
      - uses: khan/pull-request-comment-trigger@v1.1.0
        id: check
        with:
          trigger: '/regenerate-cache'
          reaction: rocket
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

      - name: Get PR ref name
        uses: actions/github-script@v6
        id: pull_request_head_ref
        with:
          result-encoding: string
          script: |
            const pr_number = context.issue.number

            console.log(pr_number)

            const pr = await github.rest.pulls.get({
              pull_number: pr_number,
              owner: context.repo.owner,
              repo: context.repo.repo,
            })

            console.log(pr)
            console.log(JSON.stringify(pr))

            return pr.head.ref

      - name: Trigger preproc
        if: steps.check.outputs.triggered == 'true'
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: cookbook_preproc.yaml
          ref: ${{ steps.pull_request_head_ref_name.outputs.result }}
          inputs: '{"pr_number": "${{ github.event.issue.number }}"}'
          token:  ${{ secrets.github_token }}
