name: Pre-process example notebooks

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Update the cache for PR#: (leave blank if not a PR)'
        required: false
        default: ""
        type: string
  schedule:
    - cron: 0 0 * * * # 1/day at midnight UTC
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}-${{ inputs.pr_number }}
  cancel-in-progress: true

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
      - name: Report dispatch to PR
        if: github.event_name == 'workflow_dispatch' && inputs.pr_number != ''
        uses: thollander/actions-comment-pull-request@v2
        with:
          pr_number: ${{inputs.pr_number}}
          message: >
            A workflow has been dispatched to regenerate the cookbook cache for this PR.


            - Run ID: [${{ github.run_id }}]

            - Triggering actor: ${{github.triggering_actor}}

            - Target branch: ${{github.ref_name}}


            [${{ github.run_id }}]: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}


      - uses: actions/checkout@v3

      - name: Install Conda environment
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: devtools/conda-envs/examples_env.yml

      - name: Checkout deployment branch
        uses: actions/checkout@v3
        with:
          ref: _cookbook_data
          path: 'deploy'
          clean: false

      - name: Choose deployment subdirectory
        shell: bash -l {0}
        run: |
          if [[ ${{ github.event_name }} != "workflow_dispatch" ]]; then
            echo "DEPLOY_SUBDIR=$GITHUB_REF_NAME" >> "$GITHUB_ENV"
          elif [[ "${{ inputs.pr_number }}" == "" ]]; then
            echo "DEPLOY_SUBDIR=$GITHUB_REF_NAME" >> "$GITHUB_ENV"
          else
            echo "DEPLOY_SUBDIR=PR${{ inputs.pr_number }}" >> "$GITHUB_ENV"
          fi

      - name: Prepare cache deployment directory
        shell: bash -l {0}
        run: |
          mkdir -p deploy/$DEPLOY_SUBDIR
          cd deploy/$DEPLOY_SUBDIR
          git config user.name github-actions
          git config user.email github-actions@github.com
          git rm -r --ignore-unmatch .

      - name: Pre-process and execute notebooks
        shell: bash -l {0}
        run: |
          python source/_ext/proc_examples.py --prefix=deploy/$DEPLOY_SUBDIR --cache-prefix=$DEPLOY_SUBDIR

      - name: Deploy cache
        shell: bash -l {0}
        run: |
          cd deploy/$DEPLOY_SUBDIR
          git add .
          git commit --amend -m "Deploy pre-processed notebook cache"
          git push --force origin _cookbook_data

      - name: Trigger RTD build
        # RTD doesn't offer a way to manually trigger builds in PRs, so we'll just do this for other builds
        if: github.event_name == 'schedule' || github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && inputs.pr_number == '')
        shell: bash -l {0}
        run: |
          curl -X POST -d "branches=$GITHUB_REF_NAME" -d "token=${{ secrets.RTD_WEBHOOK_TOKEN }}" https://readthedocs.org/api/v2/webhook/openff-docs/243876/

      - name: Report status to PR
        if: always() && github.event_name == 'workflow_dispatch' && inputs.pr_number != ''
        uses: thollander/actions-comment-pull-request@v2
        with:
          pr_number: ${{inputs.pr_number}}
          message: >
            A workflow dispatched to regenerate the cookbook cache for this PR has just finished.


            - Run ID: [${{ github.run_id }}]

            - Triggering actor: ${{github.triggering_actor}}

            - Target branch: ${{github.ref_name}}

            - Status: **${{job.status}}**


            If the workflow was successful, changes will be visible in the ReadTheDocs
            preview only after it has been rebuilt.


            [${{ github.run_id }}]: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

