name: lint

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:

  check:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Conda environment
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: devtools/conda-envs/rtd_env.yml

      - name: Check dead links
        shell: bash -l {0}
        run: |
          sphinx-build -b linkcheck source build/html
